---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    name: user
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user
  template:
    metadata:
      labels:
        name: user
    spec:
      containers:
        - name: user
          image: quay.io/powercloud/sock-shop-user:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
          command: [ "/opt/user" ]
          args: [ "-port=8080" , "-mongo-host=user-db:27017" ]
          env:
            - name: mongo
              value: user-db:27017
            - name: HATEAOS
              value: user
            - name: USER_DATABASE
              value: mongodb
          securityContext:
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 3
      nodeSelector:
        node.openshift.io/os_id: rhcos
